name: Get & save 8-gram minted photos/void data

on:
  schedule:
    - cron: '3,8,13,18,23,28,33,38,43,48,53,58 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.2.0
      - name: Create local changes
        run: node index.js
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
