name: Get & save 8-gram minted photos/void data

on:
  schedule:
    - cron: '0/5 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          node-version: 18.2.0
          persist-credentials: false
          fetch-depth: 0
      - name: Create local changes
        run: node index.js
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
